### ISSUE TITLE
--test_guid not selecting tests

### ISSUE THREAD

**Issue by phantinuss** [swimlane/atomic-operator#41]
When executing
```
atomic-operator.exe run --test_guid fe94a1c3-3e22-4dc9-9fdf-3a8bdbc10dc4 --check_preregs True --return_atomics True
```
I get listed all the atomic tests.

I would expect only the test(s) with the given guid. As the default for `--techniques`  is "all", I thought I try to disable it using`['None']` or `[]` but those do not work. I only get the empty dict:
```
atomic-operator.exe run --techniques ['None'] --test_guid 89676ba1-b1f8-47ee-b940-2e1a113ebc71 --check_preregs True --return_atomics True
{}
```
Maybe I am using it wrong? What would be the recommended way to just execute a sub test via guid?

**Comment by phantinuss** [comment]
The same seems to be true for using ``--config_file_only``:
```
atomic-operator.exe run --config_file_only ato-config.yml
{}
```
```
type .\ato-config.yml
atomic_tests:
  - guid: 89676ba1-b1f8-47ee-b940-2e1a113ebc71
  - guid: 4c4959bf-addf-4b4a-be86-8d09cc1857aa
```
