### ISSUE TITLE
Config file tests skip 

### ISSUE THREAD

**Issue by MechiH** [swimlane/atomic-operator#57]
### Description
When you put two guids of tests from the same technique the second test won't be launched, the problem is with the ConfigParser build_run_list method returns an empty list 
From what i saw that the temp.atomic_tests was overwritten the list of tests rin for that specific technique  so when you use another test from the same technqiue you won't be able to get that test because the technqiue  list of atomic tests contain only the first test guid

### To Reproduce
Launch tests  using  a config file containning guids that belongs to same technique

### Expected behavior
Atomic Operator should be able to find and launch all the test mentionned in the config file

 - OS: Windows 10

**Comment by PR0M37H3US** [comment]
I am facing a similiar problem at the moment.
I am using the the framework via python as follows:
```
at = AtomicOperator()
at.run(
     atomics_path="xxx", 
     config_file="xxx", 
     config_file_only=True
)
```

The config file looks as follows:
```
atomic_tests:
  - guid: 1b0814d1-bb24-402d-9615-1b20c50733fb
  - guid: ab39a04f-0c93-4540-9ff2-83f862c385ae
  - guid: b1636f0a-ba82-435c-b699-0d78794d8bfd
  - guid: 987901d1-5b87-4558-a6d9-cffcabc638b8
```
However it always only executes the first test and then stop.
First tries of debugging lead me to the function "__build_run_list", which is called in the configparser.
Somehow before calling it the uuids are right in the "test_dict", afterwards only the first on ends up in return_list. 
I guess that's the problem and related to this issue.

Maybe any idea how to fix my problem?
